# TWFaith Config File
# Version : Snapshot 1

# Pray cool down
pray-cool-down: 10

# Base stamina regeneration per second
base-stamina-regen: 1

# Powers
# cost: The number of faith points to purchase the upgrade
# stamina: The stamina cost (either per second or per trigger) to use the power
# cooldown: How many seconds the god must wait before triggering the power again. Only for triggered powers.

# Divine Intervention
divine-cost: 5
divine-stamina: 20
divine-cooldown: 10

# Hell's Fury
hells-cost: 5
hells-stamina: 5

# Mana
mana-cost: 5
mana-stamina: 10
mana-cooldown: 10

# Powerful Flock
flock-cost: 5
flock-stamina: 5

# Summon God
summon-cost: 5
summon-stamina: 11
summon-cooldown: 10

# Terrain Bonus
terrain-cost: 5
terrain-stamina: 5

# Lion's Heart
lions-heart-cost: 5
lions-heart-stamina: 5

# Savior
savior-cost: 5
savior-stamina: 20
savior-cooldown: 10

# Taunt
taunt-cost: 5
taunt-stamina: 20
taunt-cooldown: 10

# Insidious
insidious-cost: 5
insidious-stamina: 5

# Explosive Landing
explosive-cost: 5
explosive-stamina: 20
explosive-cooldown: 10
#Limits the size of explosions with explosive landing. This is important because if you set the number too high,
#you will risk crashing the server with the power.
explosive-max-mag: 40

# Flood
flood-cost: 5
flood-stamina: 30
flood-cooldown: 10

# Crumbling
crumbling-cost: 5
crumbling-stamina: 5

# Discombobulation
discombobulate-cost: 5
discombobulate-stamina: 100
discombobulate-cooldown: 300

# Entangle
entangle-cost: 5
entangle-stamina: 50
entangle-cooldown: 60

# Heavy Boots
heavy-cost: 5
heavy-stamina: 5

# Intoxicate
intoxicate-cost: 5
intoxicate-stamina: 5